name: pulsoxy
channels:
  - defaults
  - conda-forge
dependencies:
  - matplotlib=3.5.3
  - numpy=1.21.5
  - pandas=1.3.5
  - pip=22.3.1
  - python=3.7.15
  - scipy=1.7.3
  - websockets=8.1
  - pip:
    - hbmqtt==0.9.6
